use std::collections::HashMap;

use crab2d_scene::Scene;

use crate::{
    prompts::{
        extract_all_rhai, extract_json, extract_script_path, SCENE_SYSTEM_PROMPT,
        SCRIPT_SYSTEM_PROMPT,
    },
    AiError, AiProvider,
};

/// A scene generated by an AI provider together with any associated scripts.
pub struct GeneratedGame {
    /// The scene, ready to be saved or handed straight to the runtime.
    pub scene: Scene,
    /// Script file path → Rhai source code.
    pub scripts: HashMap<String, String>,
    /// Raw AI response, useful for debugging.
    pub raw_response: String,
}

/// A standalone script generated by an AI provider.
pub struct GeneratedScript {
    /// Suggested file path (e.g. `scripts/player.rhai`).
    pub path: String,
    /// Rhai source code.
    pub source: String,
    /// Raw AI response, useful for debugging.
    pub raw_response: String,
}

/// High-level AI interface for generating Crab2D content.
///
/// ```no_run
/// use crab2d_ai::{GameAi, AnthropicProvider};
///
/// let provider = AnthropicProvider::new(std::env::var("ANTHROPIC_API_KEY").unwrap());
/// let ai = GameAi::new(provider);
/// let game = ai.generate_game("a top-down dungeon crawler with a player and three coin pickups").unwrap();
/// println!("Generated scene: {}", game.scene.name);
/// ```
pub struct GameAi {
    provider: Box<dyn AiProvider>,
}

impl GameAi {
    pub fn new(provider: impl AiProvider + 'static) -> Self {
        Self {
            provider: Box::new(provider),
        }
    }

    /// Generate a complete scene + scripts from a free-text description.
    pub fn generate_game(&self, description: &str) -> Result<GeneratedGame, AiError> {
        let user = format!(
            "Create a Crab2D game with the following description:\n\n{description}\n\n\
             Return the scene JSON and all required Rhai scripts."
        );

        let raw = self.provider.complete(SCENE_SYSTEM_PROMPT, &user)?;
        let scene = parse_scene(&raw)?;
        let scripts = collect_scripts(&raw);

        Ok(GeneratedGame {
            scene,
            scripts,
            raw_response: raw,
        })
    }

    /// Generate only a scene (no scripts) from a free-text description.
    pub fn generate_scene(&self, description: &str) -> Result<Scene, AiError> {
        let user = format!(
            "Create a Crab2D scene with the following description:\n\n{description}\n\n\
             Return only the scene JSON. No scripts needed."
        );

        let raw = self.provider.complete(SCENE_SYSTEM_PROMPT, &user)?;
        parse_scene(&raw)
    }

    /// Generate a single Rhai script from a free-text description.
    ///
    /// `suggested_path` becomes the returned `GeneratedScript::path` when the AI
    /// does not embed a `// path:` comment in its response.
    pub fn generate_script(
        &self,
        description: &str,
        suggested_path: &str,
    ) -> Result<GeneratedScript, AiError> {
        let raw = self.provider.complete(SCRIPT_SYSTEM_PROMPT, description)?;
        let source = extract_rhai_source(&raw)?;
        let path = extract_script_path(&raw).unwrap_or_else(|| suggested_path.to_owned());
        Ok(GeneratedScript {
            path,
            source,
            raw_response: raw,
        })
    }

    /// Refine an existing scene with a follow-up instruction.
    ///
    /// The current scene JSON is embedded in the prompt so the AI can
    /// see what already exists and make targeted additions or changes.
    pub fn refine_scene(
        &self,
        current_scene: &Scene,
        instruction: &str,
    ) -> Result<GeneratedGame, AiError> {
        let current_json =
            serde_json::to_string_pretty(current_scene).map_err(AiError::Deserialize)?;

        let user = format!(
            "Here is the current Crab2D scene JSON:\n\n```json\n{current_json}\n```\n\n\
             Apply the following change:\n\n{instruction}\n\n\
             Return the complete updated scene JSON and any new or modified Rhai scripts."
        );

        let raw = self.provider.complete(SCENE_SYSTEM_PROMPT, &user)?;
        let scene = parse_scene(&raw)?;
        let scripts = collect_scripts(&raw);

        Ok(GeneratedGame {
            scene,
            scripts,
            raw_response: raw,
        })
    }
}

// ─── helpers ─────────────────────────────────────────────────────────────────

fn parse_scene(raw: &str) -> Result<Scene, AiError> {
    let json_text = extract_json(raw).ok_or(AiError::NoJsonFound)?;
    serde_json::from_str(json_text).map_err(AiError::Deserialize)
}

fn extract_rhai_source(raw: &str) -> Result<String, AiError> {
    crate::prompts::extract_rhai(raw)
        .map(str::to_owned)
        .ok_or(AiError::NoJsonFound)
}

/// Walk the raw response and collect every ```rhai block together with its
/// optional preceding `// path: …` comment into a HashMap<path, source>.
fn collect_scripts(raw: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let blocks = extract_all_rhai(raw);
    let mut remaining = raw;

    for block in blocks {
        // Find the text that precedes this block in the remaining response.
        if let Some(pos) = remaining.find(block) {
            let before = &remaining[..pos];
            let path = extract_script_path(before)
                .unwrap_or_else(|| format!("scripts/script_{}.rhai", map.len()));
            map.insert(path, block.to_owned());
            remaining = &remaining[pos + block.len()..];
        }
    }

    map
}

#[cfg(test)]
mod tests {
    use super::*;

    struct EchoProvider(String);
    impl AiProvider for EchoProvider {
        fn complete(&self, _system: &str, _user: &str) -> Result<String, AiError> {
            Ok(self.0.clone())
        }
    }

    fn minimal_scene_response() -> &'static str {
        r#"```json
{
  "name": "TestScene",
  "next_id": 1,
  "nodes": [{"id": 0, "name": "Root", "transform": {"position": {"x": 0.0, "y": 0.0}, "rotation_radians": 0.0, "scale": {"x": 1.0, "y": 1.0}}}],
  "components": {
    "tags": {}, "sprites": {}, "cameras": {}, "tilemaps": {},
    "velocities": {}, "colliders": {}, "player_controllers": {},
    "camera_follows": {}, "triggers": {}, "behaviors": {}, "audios": {},
    "animations": {}, "ui_labels": {}, "ui_panels": {}, "particle_emitters": {}
  },
  "physics_settings": {"gravity": {"x": 0.0, "y": -980.0}, "terminal_velocity": 1200.0, "enabled": false}
}
```"#
    }

    #[test]
    fn generate_scene_parses_minimal_response() {
        let ai = GameAi::new(EchoProvider(minimal_scene_response().to_owned()));
        let scene = ai.generate_scene("a test scene").unwrap();
        assert_eq!(scene.name, "TestScene");
        assert_eq!(scene.nodes().len(), 1);
    }

    #[test]
    fn generate_game_collects_scripts() {
        let response = format!(
            "{}\n// path: scripts/player.rhai\n```rhai\nfn on_update(dt) {{}}\n```",
            minimal_scene_response()
        );
        let ai = GameAi::new(EchoProvider(response));
        let game = ai.generate_game("test").unwrap();
        assert!(game.scripts.contains_key("scripts/player.rhai"));
    }

    #[test]
    fn errors_when_no_json_block() {
        let ai = GameAi::new(EchoProvider("no json here".to_owned()));
        assert!(matches!(
            ai.generate_scene("x").unwrap_err(),
            AiError::NoJsonFound
        ));
    }
}
